# Generated by Django 5.1.4 on 2025-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('forwarded_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('cookies', models.JSONField()),
                ('headers', models.JSONField()),
                ('query_params', models.JSONField()),
                ('post_data', models.JSONField()),
                ('geolocation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
